# bank_config.py
# 银行数据字段映射配置

# 正则表达式配置
REG_STR = r'\t| |"|\\\\|(nan)|\\|,'
REG_TIME_STR = r'\D|\b0\b'

# 字段映射字典
NAME_DICT = {
    '人员信息': {
        'source': 'on',
        'realName': ['客户名称\t', 'str'],
        'idType': ['证照类型\t', 'str'],
        'idNum': ['证照号码\t', 'str'],
        'nowLoc': ['现住址_行政区划\t', 'none'],
        'workLocation': ['单位地址\t', 'str'],
        'contactNum': ['联系电话\t', 'str'],
        'concatPhone': ['联系手机\t', 'str'],
        'workPhone': ['单位电话\t', 'str'],
        'HomePhone': ['住宅电话\t', 'str'],
        'workUnit': ['工作单位\t', 'str'],
        'mailAddress': ['邮箱地址\t', 'str'],
        'agentName': ['代办人姓名\t', 'str'],
        'agentIdType': ['代办人证件类型\t', 'str'],
        'agentId': ['代办人证件号码\t', 'str'],
        'nationalTaxpaymentNum': ['国税纳税号\t', 'str'],
        'localTaxPaymentNum': ['地税纳税号\t', 'none'],
        'legalRepresentative': ['法人代表\t', 'str'],
        'legalRepresentativeIdtype': ['法人代表证件类型\t', 'str'],
        'legalRepresentativeIdNum': ['法人代表证件号码\t', 'str'],
        'birth': ['出生日期\t', 'str'],
        'Registeredaddress': ['户籍地址\t', 'str'],
        'CustomersBusinessLicenseNumber': ['客户工商执照号码\t', 'str']
    },
    '账户信息': {
        'source': 'on',
        'accountOpeningName': ['账户开户名称\t', 'str'],
        'idNum': ['开户人证件号码\t', 'str'],
        'transactionCardNum': ['交易卡号\t', 'card_no'],
        'tradingAccountNum': ['交易账号\t', 'card_no'],
        'accountOpeningTime': ['账号开户时间\t', 'datetime'],
        'accountBalance': ['账户余额\t', 'float'],
        'availableBalance': ['可用余额\t', 'float'],
        'currency': ['币种\t', 'str'],
        'accountOpeningOutletCode': ['开户网点代码\t', 'str'],
        'accountOpeningOutlets': ['开户网点\t', 'str'],
        'accountStatus': ['账户状态\t', 'str'],
        'banknoteLogo': ['炒汇标志名称\t', 'str'],
        'accountClosureDate': ['销户日期\t', 'datetime'],
        'accountType': ['账户类型\t', 'str'],
        'contactInformation': ['开户联系方式\t', 'str'],
        'mailAddress': ['通信地址\t', 'str'],
        'contactNum': ['联系电话\t', 'str'],
        'agent': ['代理人\t', 'str'],
        'phoneNumber': ['代理人电话\t', 'str'],
        'remark': ['备注\t', 'none'],
        'openingProvince': ['开户省份\t', 'str'],
        'openingCity': ['开户城市\t', 'str'],
        'accountOpeningBank': ['账号开户银行\t', 'str'],
        'customerCode': ['客户代码\t', 'str'],
        'legalRepresentative': ['法人代表\t', 'str'],
        'CustomersBusinessLicenseNumber': ['客户工商执照号码\t', 'str'],
        'legalRepresentativeIdNum': ['法人代表证件号码\t', 'str'],
        'residentialAddress': ['住宅地址\t', 'str'],
        'PostalCode': ['邮政编码\t', 'str'],
        'agentId': ['代办人证件号码\t', 'str'],
        'emailAddress': ['邮箱地址\t', 'str'],
        'fundAccount': ['关联资金账户\t', 'str'],
        'localTaxPaymentNum': ['地税纳税号\t', 'str'],
        'workPhone': ['单位电话\t', 'str'],
        'agentIdType': ['代办人证件类型\t', 'str'],
        'HomePhone': ['住宅电话\t', 'str'],
        'legalRepresentativeIdtype': ['法人代表证件类型\t', 'str'],
        'nationalTaxpaymentNum': ['国税纳税号\t', 'str'],
        'workLocation': ['单位地址\t', 'str'],
        'workUnit': ['工作单位\t', 'str'],
        'closingBranch': ['销户网点\t', 'str'],
        'closureOutlets': ['账户销户银行\t', 'str'],
        'lastTradingTime': ['最后交易时间\t', 'datetime']
    },
    '子账户信息': {
        'source': 'on',
        'bank_name': ['银行名称\t', 'none'],
        'openAnAccount': ['开户账号\t', 'card_no'],
        'subAccountAccounts': ['子账户账号\t', 'str'],
        'balance': ['余额\t', 'float'],
        'availableBalance': ['可用余额\t', 'float'],
        'subAccountType': ['子账户类别\t', 'str'],
        'subAccountSerialNum': ['账户序号\t', 'str'],
        'currency': ['币种\t', 'str'],
        'banknoteLogo': ['钞汇标识\t', 'str'],
        'accountStatus': ['账户状态\t', 'str'],
        'accountId': ['账户序号\t', 'none']
    },
    '强制措施信息': {
        'source': 'on',
        'bankName': ['银行名称\t', 'none'],
        'account': ['账号\t', 'card_no'],
        'TypeOfFreezingAction': ['冻结措施类型\t', 'str'],
        'freezeAmount': ['冻结金额\t', 'float'],
        'freezeTheAuthorities': ['冻结机关\t', 'str'],
        'freezeStartDate': ['冻结开始日期\t', 'datetime'],
        'freezeDeadline': ['冻结截止日期\t', 'datetime'],
        'serialNum': ['措施序号\t', 'str'],
        'remark': ['备注\t', 'str']
    },
    '交易明细': {
        'card_no': ['交易卡号\t', 'card_no'],
        'card_account': ['交易账号\t', 'card_no'],
        'result': ['查询反馈结果原因\t', 'none'],
        'account_name': ['交易户名\t', 'str'],
        'idNumber': ['交易证件号码\t', 'str'],
        'idType': ['交易方证件类型\t', 'none'],
        'trade_date': ['交易时间\t', 'datetime'],
        'trade_money': ['交易金额\t', 'float'],
        'trade_balance': ['交易余额\t', 'float'],
        'dict_trade_tag': ['收付标志\t', 'tag'],
        'rival_card_no': ['交易对手账卡号\t', 'card_no'],
        'cash_sign': ['现金标志\t', 'str'],
        'rival_card_name': ['对手户名\t', 'str'],
        'rival_card_id_no': ['对手身份证号\t', 'str'],
        'rival_card_bank_name': ['对手开户银行\t', 'str'],
        'summary_description': ['摘要说明\t', 'str'],
        'transaction_currency': ['交易币种\t', 'str'],
        'transaction_outlet_name': ['交易网点名称\t', 'str'],
        'transaction_loc': ['交易发生地\t', 'str'],
        'is_transaction_v': ['交易是否成功\t', 'str'],
        'subpoena_num': ['传票号\t', 'str'],
        'ip_loc': ['IP地址\t', 'str'],
        'mac_loc': ['MAC地址\t', 'str'],
        'rival_trade_balance': ['对手交易余额\t', 'float'],
        'transaction_serial_num': ['交易流水号\t', 'str'],
        'log_num': ['日志号\t', 'str'],
        'credential_type': ['凭证种类\t', 'str'],
        'voucher_num': ['凭证号\t', 'str'],
        'transaction_teller_num': ['交易柜员号\t', 'str'],
        'remark': ['备注\t', 'str'],
        'merchant_name': ['商户名称\t', 'none'],
        'merchant_code': ['商户代码\t', 'none'],
        'transaction_type': ['交易类型\t', 'none']
    },
    "失败信息": {
        "task_serial_number": ['任务流水号\t', 'str'],
        "bank_name": ['银行名称\t', 'str'],
        "main_category": ['主体类别\t', 'str'],
        "certificate_number": ['证账号码\t', 'str'],
        "account_card_number": ['账卡号\t', 'str'],
        "send_time": ['发送时间\t', 'datetime'],
        "feedback_time": ['反馈时间\t', 'datetime'],
        "feedback_result": ['反馈结果\t', 'str'],
        "warehouse_status": ['入库状态\t', 'str'],
        "request_number": ['请求单号\t', 'str'],
        "query_result": ['查询结果\t', 'str']
    }
}
